api_output_for_empty_months = """"Usage Data Extract",
    "",
    "AccountOwnerId","Account Name","ServiceAdministratorId","SubscriptionId","SubscriptionGuid","Subscription Name","Date","Month","Day","Year","Product","Meter ID","Meter Category","Meter Sub-Category","Meter Region","Meter Name","Consumed Quantity","ResourceRate","ExtendedCost","Resource Location","Consumed Service","Instance ID","ServiceInfo1","ServiceInfo2","AdditionalInfo","Tags","Store Service Identifier","Department Name","Cost Center","Unit Of Measure","Resource Group",'
    """
sample_data = [{u'AccountName': u'Platform',
  u'AccountOwnerId': u'donald.duck',
  u'AdditionalInfo': u'',
  u'ConsumedQuantity': 23.0,
  u'ConsumedService': u'Virtual Network',
  u'CostCenter': u'1234',
  u'Date': u'03/01/2017',
  u'Day': 1,
  u'DepartmentName': u'Engineering',
  u'ExtendedCost': 0.499222332425423563466,
  u'InstanceId': u'platform-vnet',
  u'MeterCategory': u'Virtual Network',
  u'MeterId': u'c90286c8-adf0-438e-a257-4468387df385',
  u'MeterName': u'Hours',
  u'MeterRegion': u'All',
  u'MeterSubCategory': u'Gateway Hour',
  u'Month': 3,
  u'Product': u'Windows Azure Compute 100 Hrs Virtual Network',
  u'ResourceGroup': u'',
  u'ResourceLocation': u'All',
  u'ResourceRate': 0.0304347826086957,
  u'ServiceAdministratorId': u'',
  u'ServiceInfo1': u'',
  u'ServiceInfo2': u'',
  u'StoreServiceIdentifier': u'',
  u'SubscriptionGuid': u'abc3455ac-3feg-2b3c5-abe4-ec1111111e6',
  u'SubscriptionId': 23467313421,
  u'SubscriptionName': u'Production',
  u'Tags': u'',
  u'UnitOfMeasure': u'Hours',
  u'Year': 2017},
 {u'AccountName': u'Platform',
  u'AccountOwnerId': u'donald.duck',
  u'AdditionalInfo': u'',
  u'ConsumedQuantity': 0.064076,
  u'ConsumedService': u'Microsoft.Storage',
  u'CostCenter': u'1234',
  u'Date': u'03/01/2017',
  u'Day': 1,
  u'DepartmentName': u'Engineering',
  u'ExtendedCost': 0.50000011123124314235234522345,
  u'InstanceId': u'/subscriptions/abc3455ac-3feg-2b3c5-abe4-ec1111111e6/resourceGroups/my-group/providers/Microsoft.Storage/storageAccounts/ss7q3264domxo',
  u'MeterCategory': u'Windows Azure Storage',
  u'MeterId': u'd23a5753-ff85-4ddf-af28-8cc5cf2d3882',
  u'MeterName': u'Standard IO - Page Blob/Disk (GB)',
  u'MeterRegion': u'All Regions',
  u'MeterSubCategory': u'Locally Redundant',
  u'Month': 3,
  u'Product': u'Locally Redundant Storage Standard IO - Page Blob/Disk',
  u'ResourceGroup': u'my-group',
  u'ResourceLocation': u'euwest',
  u'ResourceRate': 0.0377320156152495,
  u'ServiceAdministratorId': u'',
  u'ServiceInfo1': u'',
  u'ServiceInfo2': u'',
  u'StoreServiceIdentifier': u'',
  u'SubscriptionGuid': u'abc3455ac-3feg-2b3c5-abe4-ec1111111e6',
  u'SubscriptionId': 23467313421,
  u'SubscriptionName': u'Production',
  u'Tags': None,
  u'UnitOfMeasure': u'GB',
  u'Year': 2017}]
